$schema: "http://json-schema.org/draft-06/schema#"
description: Configuration parameters for running pipeline
properties:
  h1:
    type: string
    description: h1 adaptor sequnce, appears before barcode in read1
    default: CAGTTGATCATCAGCAGGTAATCTGG
  h2:
    type: string
    description: h2 adaptor sequence, appears after barcode in read1
    default: CATGACCTCTTGGAACTGTCAGATGTGTATAAGAGACAG
  h3:
    type: string
    description: h3 adaptor sequence, appears after genomics insert in read1 and read2.
    default: CTGTCTCTTATACACATCT
  barcode:
    type: string
    description: Barcode sequence
    default: BDHVBDHVBDHVBDHVBDHV
  index:
    type: ["null", "string"]
    description: Path to index file containing the barcode
    default: null
  barcode_max_dist:
    type: integer
    description: Max edit distance (Leveshtein distance) allowed to cluster two barcode sequences together
    default: 2
  barcode_ratio:
    type: integer
    description: Starcode parameter. Minimum difference in ratio for read count to cluster nodes
    default: 5
  min_count:
    type: integer
    description: Minimum number of reads to include barcode in alignment
    default: 1
  reference:
    type: ["null", "string"]
    description: Path to BWA indexed reference
  reference_name:
    type: string
    description: Name of reference genome. See options in GENOMELIST (https://github.com/r3fang/SnapTools/blob/master/snaptools/global_var.py)
    default: hg38
  bin_sizes:
    type: ["string", "integer"]
    description: Space separated integers of SnapTools bin sizes use for matrix generation
    default: "5000 10000"
    pattern: '^[0-9]+(\s[0-9]+)*$'
