title: "DBS-OCP run report"
intro_text: "This is a collection of results from the DBS-OCP pipeline. Go to our
<a href=https://github.com/AfshinLab/DBS-OCP>github page</a> for more information."

fn_ignore_dirs:
    - '.snakemake'

run_modules:
    - fastqc
    - cutadapt
    - custom_content
    - samblaster

module_order:
    - cutadapt:
        name: "Cutadapt (inserts)"
        info: "run to extract inserts"
        anchor: "cutadapt_inserts"
        target: ""
        path_filters:
            - "*trimmed.fastq.log"
    - cutadapt:
        name: "Cutadapt (barcodes)"
        info: "run to extract barcodes"
        anchor: "cutadapt_barcodes"
        path_filters:
            - "*barcodes.fastq.gz.log"
    - fastqc:
        name: "FastQC (insert)"
        info: "FastQC run on the trimmed inserts"
        anchor: "fastqc_trimmed"
        target: ""
        path_filters:
            - "*trimmed.barcoded*"
    - fastqc:
        name: "FastQC (barcodes)"
        anchor: "fastqc_barcodes"
        info: "FastQC run on the extracted barcodes"
        path_filters:
          - "*barcodes*"

sp:
    fastqc:
        fn: "*fastqc.zip"
