# Whenever this file is updated, you need to run misc/condalock.sh to create
# the environment.lock.yml file.
name: dbsocp
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.8
  - bioconda::cutadapt
  - conda-forge::python-isal>0.8.0 # See https://github.com/marcelm/cutadapt/issues/520
  - bioconda::bwa
  - bioconda::samtools
  - bioconda::snakemake-minimal
  - bioconda::starcode
  - conda-forge::tqdm
  - conda-forge::ruamel.yaml
  - conda-forge::importlib_resources
  - bioconda::fastqc
  - bioconda::multiqc
  - bioconda::samblaster
  - pip
  - pip:
      - snaptools
