# Whenever this file is updated, you need to run misc/condalock.sh to create
# the environment.lock.yml file.
name: dbsocp
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::importlib_resources # Remove when minimum Python verion is 3.9
  - conda-forge::pip
  - conda-forge::python>=3.8
  - conda-forge::python-isal>0.8.0 # See https://github.com/marcelm/cutadapt/issues/520
  - conda-forge::ruamel.yaml
  - conda-forge::scipy
  - conda-forge::tqdm
  - conda-forge::pandas
  - bioconda::cutadapt=4.4
  - bioconda::bwa=0.7.17
  - bioconda::fastqc=0.12.1
  - bioconda::multiqc
  - bioconda::preseq
  - bioconda::samtools>=1.17
  - bioconda::sinto=0.9.0
  - bioconda::snakemake-minimal>=7.28.1
  - bioconda::starcode=1.4
  - pip:
      - snaptools
