name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths-ignore:
      - 'doc/**'
      - 'README.md'
jobs:
  run:
    name: Run pipeline
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.8
          mamba-version: "*"
          channels: conda-forge,bioconda,defaults
          channel-priority: true
          activate-environment: testenv
          environment-file: environment.yml
      - name: Install package
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate testenv
          pip install .[dev]
      - name: Run black check
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate testenv
          black --check src/ tests/
      - name: Run flake8
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate testenv
          flake8 src/ tests/
          flake8 --select=W292 --filename '*.yaml,*.yml'
      - name: Run tests
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate testenv
          pytest -v tests/
