name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  run:
    name: Run pipeline
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Conda environment
        run: |
          conda info
          envfile=environment.yml
          conda env create -n testenv -f ${envfile}
          conda install -n testenv flake8 pytest
      - name: Run flake8
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate testenv
          flake8 src/ tests/
          flake8 --select=W292 --filename '*.yaml,*.yml'
      - name: Run tests
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate testenv
          pip install -e .
          pytest -v tests/
